import { expect, test } from '@playwright/test'

// Client-only: the settings page's account security sections, with every
// request they make stubbed here.
const signedIn = async (page: import('@playwright/test').Page) => {
  await page.addInitScript(() => {
    localStorage.setItem('eunha:token', 'test-token')
    localStorage.setItem(
      'eunha:me-account',
      JSON.stringify({ id: '1', acct: 'alice', defaultVisibility: 'public' }),
    )
  })
}

const json = (body: unknown) => ({
  status: 200,
  contentType: 'application/json',
  body: JSON.stringify(body),
})

test('two-factor setup shows the secret, then the recovery codes', async ({ page }) => {
  await signedIn(page)
  let status = {
    otp_enabled: false,
    webauthn_enabled: false,
    required: false,
    recovery_codes_remaining: 0,
    webauthn_credentials: [],
    available: true,
  }
  const sent: Record<string, unknown> = {}
  await page.route('**/api/eunha/v1/two_factor_authentication', (route) =>
    route.fulfill(json(status)),
  )
  await page.route('**/api/eunha/v1/two_factor_authentication/otp', async (route) => {
    sent.setup = route.request().postDataJSON()
    await route.fulfill(
      json({
        secret: 'JBSWY3DPEHPK3PXP',
        provisioning_uri: 'otpauth://totp/x',
        qr_code: '<svg xmlns="http://www.w3.org/2000/svg"></svg>',
      }),
    )
  })
  await page.route('**/api/eunha/v1/two_factor_authentication/otp/confirm', async (route) => {
    sent.confirm = route.request().postDataJSON()
    status = { ...status, otp_enabled: true, recovery_codes_remaining: 2 }
    await route.fulfill(json({ recovery_codes: ['0123456789abcdef', 'fedcba9876543210'] }))
  })

  await page.goto('/settings')
  await expect(page.getByRole('heading', { name: 'Two-factor authentication' })).toBeVisible()
  const section = page.locator('section', { hasText: 'Two-factor authentication' })
  await section.getByLabel('Current password').fill('hunter2hunter2')
  await section.getByRole('button', { name: 'Set up' }).click()

  await expect(page.getByText('JBSWY3DPEHPK3PXP')).toBeVisible()
  expect(sent.setup).toEqual({ password: 'hunter2hunter2' })
  await page.getByLabel('Enter the code generated by your authenticator app to confirm').fill('123456')
  await page.getByRole('button', { name: 'Enable' }).click()

  await expect(page.getByText('0123456789abcdef')).toBeVisible()
  expect(sent.confirm).toEqual({ otp_attempt: '123456' })
  await page.getByRole('button', { name: 'Done' }).click()
  await expect(page.getByText('Two-factor authentication is enabled')).toBeVisible()
})

test('sessions and authorized apps can be revoked', async ({ page }) => {
  await signedIn(page)
  let sessions = [
    {
      id: '7',
      ip: '192.0.2.1',
      user_agent: 'Firefox',
      browser: 'firefox',
      platform: 'mac',
      description: 'Firefox on macOS',
      created_at: '2026-10-01T00:00:00.000Z',
      updated_at: '2026-10-01T00:00:00.000Z',
      current: false,
    },
  ]
  let revoked = ''
  await page.route('**/api/eunha/v1/sessions', (route) => route.fulfill(json(sessions)))
  await page.route('**/api/eunha/v1/sessions/7', async (route) => {
    revoked = route.request().method()
    sessions = []
    await route.fulfill(json({}))
  })
  await page.route('**/api/eunha/v1/authorized_applications', (route) =>
    route.fulfill(
      json([
        {
          id: '3',
          name: 'Ivory',
          website: null,
          scopes: ['read', 'write'],
          superapp: false,
          last_used_at: null,
          created_at: '2026-09-01T00:00:00.000Z',
        },
      ]),
    ),
  )

  await page.goto('/settings')
  await expect(page.getByText('Firefox on macOS')).toBeVisible()
  await expect(page.getByText('Ivory')).toBeVisible()
  await page
    .locator('section', { hasText: 'Sessions' })
    .getByRole('button', { name: 'Revoke' })
    .click()
  await expect(page.getByText('Session successfully revoked')).toBeVisible()
  expect(revoked).toBe('DELETE')
  await expect(page.getByText('Firefox on macOS')).toBeHidden()
})
